version: "3.3"

services:
  be: 
    build: .
    command: bash -c "cd src && ./../node_modules/.bin/sequelize db:migrate && cd .. && node src/app.js"
    depends_on:
      - db
    links: 
      - db
    ports:
      - "3000:3000"
  db:
    image: postgres
    
    expose: 
      - "5432"
    environment: 
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "db"
      POSTGRES_DB: "db"

